### PR TITLE
Add MacOS support

### PR DESCRIPTION
**Pull request by kimdoyun0208**

### CODE REVIEW

**Comment by lavovaLampa** [comment]
Hey, thanks for the PR. I'll merge it during the weekend. I don't have any Mac device, so I'll take your word that it works 😀

**Comment by kimdoyun0208** [comment]
I'm waiting for your merge 😆

**Comment by kimdoyun0208** [comment]
> Hey, thanks for the PR. I'll merge it during the weekend. I don't have any Mac device, so I'll take your word that it works 😀

I'm waiting for your merge 😆

**Comment by lavovaLampa** [comment]
sorry, done

**Pull request merged**
